name: Supabase Keep Alive

on:
  schedule:
    # Jalankan setiap hari jam 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Insert ping record into keepalive table
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"pinged_at": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"}' \
            "https://<PROJECT-REF>.supabase.co/rest/v1/keepalive" || true
